# Generated by Django 5.2.1 on 2025-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_LoL', '0002_article_avisbuild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='rune_major',
        ),
        migrations.RemoveField(
            model_name='build',
            name='rune_minor',
        ),
        migrations.AddField(
            model_name='build',
            name='keystone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='primary_path',
            field=models.CharField(blank=True, choices=[('Precision', 'Precision'), ('Domination', 'Domination'), ('Sorcery', 'Sorcery'), ('Resolve', 'Resolve'), ('Inspiration', 'Inspiration')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='primary_slot1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='primary_slot2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='primary_slot3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='secondary_path',
            field=models.CharField(blank=True, choices=[('Precision', 'Precision'), ('Domination', 'Domination'), ('Sorcery', 'Sorcery'), ('Resolve', 'Resolve'), ('Inspiration', 'Inspiration')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='secondary_slot1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='secondary_slot2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='shard_defense',
            field=models.CharField(blank=True, choices=[('adaptive_force', 'Adaptive Force'), ('attack_speed', 'Attack Speed'), ('ability_haste', 'Ability Haste'), ('movement_speed', 'Movement Speed'), ('bonus_health', 'Bonus Health'), ('tenacity', 'Tenacity and Slow Resist')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='shard_flex',
            field=models.CharField(blank=True, choices=[('adaptive_force', 'Adaptive Force'), ('attack_speed', 'Attack Speed'), ('ability_haste', 'Ability Haste'), ('movement_speed', 'Movement Speed'), ('bonus_health', 'Bonus Health'), ('tenacity', 'Tenacity and Slow Resist')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='shard_offense',
            field=models.CharField(blank=True, choices=[('adaptive_force', 'Adaptive Force'), ('attack_speed', 'Attack Speed'), ('ability_haste', 'Ability Haste'), ('movement_speed', 'Movement Speed'), ('bonus_health', 'Bonus Health'), ('tenacity', 'Tenacity and Slow Resist')], max_length=30, null=True),
        ),
    ]
