# Generated by Django 5.2.1 on 2025-05-13 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_LoL', '0003_remove_build_rune_major_remove_build_rune_minor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisbuild',
            name='date_poste',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
