# Generated by Django 5.2.1 on 2025-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_LoL', '0004_alter_avisbuild_date_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
