# Generated by Django 5.2.1 on 2025-05-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_LoL', '0005_build_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_path', models.CharField(max_length=255)),
            ],
        ),
    ]
