# Generated by Django 5.2.1 on 2025-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_LoL', '0006_rune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='shard_defense',
            field=models.CharField(choices=[('StatModsAdaptiveForceIcon', 'Adaptive Force'), ('StatModsAttackSpeedIcon', 'Attack Speed'), ('StatModsCDRScalingIcon', 'Ability Haste'), ('StatModsMoveSpeedIcon', 'Movement Speed'), ('StatModsHealthScalingIcon', 'Bonus Health'), ('StatModsMagicResIcon', 'Magic Resist'), ('StatModsArmorIcon', 'Armor')], default='StatModsHealthScalingIcon', max_length=64),
        ),
        migrations.AlterField(
            model_name='build',
            name='shard_flex',
            field=models.CharField(choices=[('StatModsAdaptiveForceIcon', 'Adaptive Force'), ('StatModsAttackSpeedIcon', 'Attack Speed'), ('StatModsCDRScalingIcon', 'Ability Haste'), ('StatModsMoveSpeedIcon', 'Movement Speed'), ('StatModsHealthScalingIcon', 'Bonus Health'), ('StatModsMagicResIcon', 'Magic Resist'), ('StatModsArmorIcon', 'Armor')], default='StatModsAdaptiveForceIcon', max_length=64),
        ),
        migrations.AlterField(
            model_name='build',
            name='shard_offense',
            field=models.CharField(choices=[('StatModsAdaptiveForceIcon', 'Adaptive Force'), ('StatModsAttackSpeedIcon', 'Attack Speed'), ('StatModsCDRScalingIcon', 'Ability Haste'), ('StatModsMoveSpeedIcon', 'Movement Speed'), ('StatModsHealthScalingIcon', 'Bonus Health'), ('StatModsMagicResIcon', 'Magic Resist'), ('StatModsArmorIcon', 'Armor')], default='StatModsAdaptiveForceIcon', max_length=64),
        ),
    ]
