# Generated by Django 5.2.1 on 2025-05-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_LoL', '0008_alter_build_shard_defense_alter_build_shard_flex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='shard_defense',
            field=models.CharField(choices=[('StatModsAdaptiveForceIcon', 'Adaptive Force'), ('StatModsArmorIcon', 'Armor'), ('StatModsAttackSpeedIcon', 'Attack Speed'), ('StatModsCDRScalingIcon', 'Ability Haste'), ('StatModsHealthScalingIcon', 'Bonus Health'), ('StatModsMagicResIcon', 'Magic Resist'), ('StatModsMoveSpeedIcon', 'Movement Speed')], default='StatModsArmorIcon', max_length=64),
        ),
        migrations.AlterField(
            model_name='build',
            name='shard_flex',
            field=models.CharField(choices=[('StatModsAdaptiveForceIcon', 'Adaptive Force'), ('StatModsArmorIcon', 'Armor'), ('StatModsAttackSpeedIcon', 'Attack Speed'), ('StatModsCDRScalingIcon', 'Ability Haste'), ('StatModsHealthScalingIcon', 'Bonus Health'), ('StatModsMagicResIcon', 'Magic Resist'), ('StatModsMoveSpeedIcon', 'Movement Speed')], default='StatModsAdaptiveForceIcon', max_length=64),
        ),
        migrations.AlterField(
            model_name='build',
            name='shard_offense',
            field=models.CharField(choices=[('StatModsAdaptiveForceIcon', 'Adaptive Force'), ('StatModsArmorIcon', 'Armor'), ('StatModsAttackSpeedIcon', 'Attack Speed'), ('StatModsCDRScalingIcon', 'Ability Haste'), ('StatModsHealthScalingIcon', 'Bonus Health'), ('StatModsMagicResIcon', 'Magic Resist'), ('StatModsMoveSpeedIcon', 'Movement Speed')], default='StatModsAdaptiveForceIcon', max_length=64),
        ),
    ]
